services:

  postgres:
    image: postgres:16
    container_name: 'postgres'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : 'user'
      POSTGRES_PASSWORD : 'password'
      POSTGRES_DB : 'resto_compras'
    volumes:
      - my-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Change this to your desired pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: password # Change this to a strong password for pgAdmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9000:80"
    depends_on:
      - postgres

volumes:
  my-db: