---
--- SCRIPT SQL COMPLETO: INSERCIÓN DE CATEGORÍAS, SUBCATEGORÍAS Y PRODUCTOS
--- Este script está diseñado para PostgreSQL, utilizando la sintaxis de valores
--- con cláusulas WHERE NOT EXISTS para evitar duplicados.
---

-- 1. CATEGORIAS (LEVEL 0)
INSERT INTO public.categories(name)
SELECT T.name
FROM (VALUES ('Almacén'),
             ('Frescos'),
             ('Congelados'),
             ('Limpieza'),
             ('Equipamineto'),
             ('Bazar'),
             ('Descartables'),
             ('Bebidas'))
         AS T(name)
WHERE NOT EXISTS (SELECT 1
                  FROM public.categories C
                  WHERE C.name = T.name);

-- 2. SUB CATEGORY LEVEL 1 (N1)
INSERT INTO public.sub_category_level1 (name, category_id)
SELECT T.sub_category_level1_name, C.id
FROM (VALUES
-- {Subcategoría N1, Categoría}
('Golosinas', 'Almacén'),
('Panadería', 'Almacén'),
('Snacks', 'Almacén'),
('Cereales', 'Almacén'),
('Endulzantes', 'Almacén'),
('Aderezos Y Salsas', 'Almacén'),
('Infusiones', 'Almacén'),
('Conservas', 'Almacén'),
('Harinas', 'Almacén'),
('Encurtidos', 'Almacén'),
('Mermeladas Y Dulces', 'Almacén'),
('Salsas Y Puré De Tomate', 'Almacén'),
('Aceites Y Condimentos', 'Almacén'),
('Arroz Y Legumbres', 'Almacén'),
('Especias', 'Almacén'),
('Pasta Seca, Lista Y Rellenas', 'Almacén'),
('Polvo Para Postres Y Repostería', 'Almacén'),
('Sopas, Caldos, Puré Y Saborizantes', 'Almacén'),
('Lácteos', 'Frescos'),
('Carnicería', 'Frescos'),
('Pescadería', 'Frescos'),
('Pastas Frescas Y Tapas', 'Frescos'),
('Fiambres Y Embutidos', 'Frescos'),
('Verdulería', 'Frescos'),
('Pescados Y Mariscos', 'Congelados'),
('Helados Y Postres', 'Congelados'),
('Nuggets, Patitas Y Bocaditos', 'Congelados'),
('Comidas Preparadas', 'Congelados'),
('Verduras Congeladas', 'Congelados'),
('Panificados Congelados', 'Congelados'),
('Limpieza de Cocina', 'Limpieza'),
('Limpieza de Baño', 'Limpieza'),
('Limpieza de Pisos', 'Limpieza'),
('Limpieza de Ropa', 'Limpieza'),
('Limpieza General', 'Limpieza'),
('Vajilla', 'Equipamineto'),
('Utensilios De Cocina', 'Equipamineto'),
('Almacenamiento', 'Equipamineto'),
('Jardín', 'Bazar'),
('Librería', 'Bazar'),
('Juguetería', 'Bazar'),
('Ferretería', 'Bazar'),
('Envases Y Bolsas', 'Descartables'),
('Mesa Y Servilletas', 'Descartables'),
('Papel', 'Descartables'),
('Bebidas Sin Alcohol', 'Bebidas'),
('Bebidas Alcohólicas', 'Bebidas')) AS T(sub_category_level1_name, category_name)
         INNER JOIN public.categories C ON C.name = T.category_name
WHERE NOT EXISTS (SELECT 1
                  FROM public.sub_category_level1 S1
                           INNER JOIN public.categories C_E ON S1.category_id = C_E.id
                  WHERE S1.name = T.sub_category_level1_name
                    AND C_E.name = T.category_name);

-- 3. SUB CATEGORY LEVEL 2 (N2)
INSERT INTO public.sub_category_level2 (name, sub_category_level1_id)
SELECT T.sub_category_level2_name, S1.id
FROM (VALUES
-- {Subcategoría N2, Subcategoría N1}
('Alfajores', 'Golosinas'),
('Chocolates', 'Golosinas'),
('Caramelos y Chupetines', 'Golosinas'),
('Chicles Y Pastillas', 'Golosinas'),
('Galletitas', 'Panadería'),
('Panadería Propia', 'Panadería'),
('Panificados', 'Panadería'),
('Galletas, Tostadas Y Grisines', 'Panadería'),
('Papas Fritas', 'Snacks'),
('Bastones De Maíz', 'Snacks'),
('Maní', 'Snacks'),
('Mix De Frutas Secas Y Semillas', 'Snacks'),
('Copos', 'Cereales'),
('Cereales', 'Cereales'),
('Azúcar', 'Endulzantes'),
('Edulcorantes', 'Endulzantes'),
('Miel', 'Endulzantes'),
('Mayonesas', 'Aderezos Y Salsas'),
('Ketchup', 'Aderezos Y Salsas'),
('Mostazas', 'Aderezos Y Salsas'),
('Salsas', 'Aderezos Y Salsas'),
('Té', 'Infusiones'),
('Mate Cocido', 'Infusiones'),
('Café', 'Infusiones'),
('Conservas De Pescado', 'Conservas'),
('Conservas De Carne', 'Conservas'),
('Conservas De Legumbres Y Vegetales', 'Conservas'),
('Vegetales en Frasco', 'Conservas'),
('Harina De Trigo', 'Harinas'),
('Harina Integral', 'Harinas'),
('Harinas Especiales', 'Harinas'),
('Pickles', 'Encurtidos'),
('Aceitunas', 'Encurtidos'),
('Ajos Y Cebollas En Conserva', 'Encurtidos'),
('Mermeladas', 'Mermeladas Y Dulces'),
('Dulce de Leche', 'Mermeladas Y Dulces'),
('Dulces', 'Mermeladas Y Dulces'),
('Puré De Tomate', 'Salsas Y Puré De Tomate'),
('Aceites', 'Aceites Y Condimentos'),
('Aceites Especiales', 'Aceites Y Condimentos'),
('Vinagres', 'Aceites Y Condimentos'),
('Condimentos', 'Aceites Y Condimentos'),
('Sales Y Pimientas', 'Aceites Y Condimentos'),
('Arroz', 'Arroz Y Legumbres'),
('Legumbres', 'Arroz Y Legumbres'),
('Pimentón', 'Especias'),
('Canela', 'Especias'),
('Comino', 'Especias'),
('Laurel', 'Especias'),
('Curry', 'Especias'),
('Condimentos Secos', 'Especias'),
('Pasta Seca', 'Pasta Seca, Lista Y Rellenas'),
('Pastas Rellenas', 'Pasta Seca, Lista Y Rellenas'),
('Polvo Para Postres', 'Polvo Para Postres Y Repostería'),
('Polvo Para Repostería', 'Polvo Para Postres Y Repostería'),
('Sopas Y Caldos', 'Sopas, Caldos, Puré Y Saborizantes'),
('Puré Instantáneo', 'Sopas, Caldos, Puré Y Saborizantes'),
('Saborizantes', 'Sopas, Caldos, Puré Y Saborizantes'),
('Leches', 'Lácteos'),
('Yogures', 'Lácteos'),
('Postres Lácteos', 'Lácteos'),
('Cremas Y Manteca', 'Lácteos'),
('Quesos', 'Lácteos'),
('Carne Vacuna', 'Carnicería'),
('Cortes Especiales', 'Carnicería'),
('Carne de Cerdo', 'Carnicería'),
('Aves', 'Carnicería'),
('Huevos', 'Carnicería'),
('Achuras', 'Carnicería'),
('Pescado', 'Pescadería'),
('Mariscos', 'Pescadería'),
('Fideos Y Ñoquis', 'Pastas Frescas Y Tapas'),
('Tapas', 'Pastas Frescas Y Tapas'),
('Fiambres', 'Fiambres Y Embutidos'),
('Embutidos', 'Fiambres Y Embutidos'),
('Frutas', 'Verdulería'),
('Verduras', 'Verdulería'),
('Hojas Verdes', 'Verdulería'),
('Hierbas Frescas', 'Verdulería'),
('Pescados', 'Pescados Y Mariscos'),
('Helados en Pote', 'Helados Y Postres'),
('Postres Congelados', 'Helados Y Postres'),
('Helados En Palito', 'Helados Y Postres'),
('Nuggets', 'Nuggets, Patitas Y Bocaditos'),
('Patitas', 'Nuggets, Patitas Y Bocaditos'),
('Bocaditos', 'Nuggets, Patitas Y Bocaditos'),
('Comidas Congeladas', 'Comidas Preparadas'),
('Vegetales Congelados', 'Verduras Congeladas'),
('Detergentes', 'Limpieza de Cocina'),
('Limpiadores', 'Limpieza de Cocina'),
('Esponjas Y Paños', 'Limpieza de Cocina'),
('Desengrasantes Industriales', 'Limpieza de Cocina'),
('Detergentes Especializados', 'Limpieza de Cocina'),
('Jabón', 'Limpieza de Ropa'),
('Suavizantes', 'Limpieza de Ropa'),
('Otros', 'Limpieza de Ropa'),
('Artículos', 'Limpieza General'),
('Platos', 'Vajilla'),
('Cubiertos', 'Vajilla'),
('Vasos', 'Vajilla'),
('Tazas', 'Vajilla'),
('Ollas Y Sartenes', 'Utensilios De Cocina'),
('Herramientas', 'Utensilios De Cocina'),
('Contenedores', 'Almacenamiento'),
('Maceteros', 'Jardín'),
('Tierra Y Abonos', 'Jardín'),
('Escritura', 'Librería'),
('Papelería', 'Librería'),
('Adhesivos', 'Librería'),
('Juegos', 'Juguetería'),
('Electricidad', 'Ferretería'),
('Bolsas', 'Envases Y Bolsas'),
('Packaging', 'Envases Y Bolsas'),
('Servilletas', 'Mesa Y Servilletas'),
('Vasos Y Platos', 'Mesa Y Servilletas'),
('Manteles', 'Mesa Y Servilletas'),
('Sobres y Sticks', 'Mesa Y Servilletas'),
('Papel Aluminio', 'Papel'),
('Film', 'Papel'),
('Papel De Cocina', 'Papel'),
('Aguas', 'Bebidas Sin Alcohol'),
('Gaseosas', 'Bebidas Sin Alcohol'),
('Jugos', 'Bebidas Sin Alcohol'),
('Mixers Premium', 'Bebidas Sin Alcohol'),
('Cervezas', 'Bebidas Alcohólicas'),
('Vinos', 'Bebidas Alcohólicas'),
('Espumantes', 'Bebidas Alcohólicas'),
('Destilados', 'Bebidas Alcohólicas'),
('Licores Y Aperitivos', 'Bebidas Alcohólicas')) AS T(sub_category_level2_name, sub_category_level1_name)
         INNER JOIN public.sub_category_level1 S1 ON S1.name = T.sub_category_level1_name
WHERE NOT EXISTS (SELECT 1
                  FROM public.sub_category_level2 S2
                           INNER JOIN public.sub_category_level1 S1_E ON S2.sub_category_level1_id = S1_E.id
                  WHERE S2.name = T.sub_category_level2_name
                    AND S1_E.name = T.sub_category_level1_name);


-- 4. PRODUCTS
INSERT INTO public.product(sub_category_level2_id, name)
SELECT SCL2.id,
       T.product_name
FROM (VALUES
          -- Almacén
          ('Alfajor', 'Alfajores'),
          ('Chocolate Cobertura', 'Chocolates'),
          ('Chocolate Negro', 'Chocolates'),
          ('Chocolate Blanco', 'Chocolates'),
          ('Tableta de Chocolate con Leche', 'Chocolates'),
          ('Caja de Bombones Surtidos', 'Chocolates'),
          ('Barra de Chocolate Semi-Amargo', 'Chocolates'),
          ('Chocolate con Frutos Secos', 'Chocolates'),
          ('Chocolate para Taza', 'Chocolates'),
          ('Chocolate sin Azúcar', 'Chocolates'),
          ('Caramelos Masticables', 'Caramelos y Chupetines'),
          ('Chupetines', 'Caramelos y Chupetines'),
          ('Bolsa de Caramelos Duros', 'Caramelos y Chupetines'),
          ('Caramelos de Miel', 'Caramelos y Chupetines'),
          ('Gomitas Frutales', 'Caramelos y Chupetines'),
          ('Pastillas de Menta Fuertes', 'Chicles Y Pastillas'),
          ('Chicles', 'Chicles Y Pastillas'),
          ('Pastillas', 'Chicles Y Pastillas'),
          ('Chicles sin Azúcar', 'Chicles Y Pastillas'),
          ('Pastillas sabor Cereza', 'Chicles Y Pastillas'),
          ('Galletitas', 'Galletitas'),
          ('Galletitas de Chocolate', 'Galletitas'),
          ('Galletitas de Vainilla', 'Galletitas'),
          ('Galletitas con Relleno de Limón', 'Galletitas'),
          ('Pan Francés', 'Panadería Propia'),
          ('Pan de Molde Integral', 'Panadería Propia'),
          ('Facturas de Crema', 'Panadería Propia'),
          ('Medialunas de Grasa', 'Panadería Propia'),
          ('Pan Lactal Clásico', 'Panadería Propia'),
          ('Baguettes', 'Panadería Propia'),
          ('Pan rallado fresco', 'Panadería Propia'),
          ('Chipás', 'Panadería Propia'),
          ('Grisines caseros', 'Panadería Propia'),
          ('Tortitas', 'Panadería Propia'),
          ('Pan de Miga', 'Panificados'),
          ('Pan de Hamburguesa', 'Panificados'),
          ('Pan de Pancho', 'Panificados'),
          ('Tostadas de Campo', 'Panificados'),
          ('Croissant envasado', 'Panificados'),
          ('Figacitas', 'Panificados'),
          ('Rapiditas', 'Panificados'),
          ('Pan Árabe', 'Panificados'),
          ('Pan Integral', 'Panificados'),
          ('Tortillas de Harina', 'Panificados'),
          ('Galletas de Agua', 'Galletas, Tostadas Y Grisines'),
          ('Galletas de Salvado', 'Galletas, Tostadas Y Grisines'),
          ('Tostadas Integrales', 'Galletas, Tostadas Y Grisines'),
          ('Grisines Comunes', 'Galletas, Tostadas Y Grisines'),
          ('Vainillas', 'Galletas, Tostadas Y Grisines'),
          ('Bizcochos de Grasa', 'Galletas, Tostadas Y Grisines'),
          ('Crackers', 'Galletas, Tostadas Y Grisines'),
          ('Galletas Marineras', 'Galletas, Tostadas Y Grisines'),
          ('Rebozador', 'Galletas, Tostadas Y Grisines'),
          ('Tostadas Clásicas', 'Galletas, Tostadas Y Grisines'),
          ('Papas Fritas Con Sal', 'Papas Fritas'),
          ('Papas Americanas', 'Papas Fritas'),
          ('Chips de Batata', 'Papas Fritas'),
          ('Papas de Corte Grueso', 'Papas Fritas'),
          ('Papas con Cebolla', 'Papas Fritas'),
          ('Papas Fritas Sin Sal', 'Papas Fritas'),
          ('Maní Salado', 'Maní'),
          ('Maní Tostado', 'Maní'),
          ('Maní con Chocolate', 'Maní'),
          ('Maní Crocante', 'Maní'),
          ('Maní Japonés', 'Maní'),
          ('Snacks Queso', 'Bastones De Maíz'),
          ('Conitos', 'Bastones De Maíz'),
          ('Bastones de Arroz inflado', 'Bastones De Maíz'),
          ('Crunchy', 'Bastones De Maíz'),
          ('Palitos de Maíz Saborizados', 'Bastones De Maíz'),
          ('Palitos Salados', 'Papas Fritas'),
          ('Mix de Frutas Secas', 'Mix De Frutas Secas Y Semillas'),
          ('Semillas de Girasol', 'Mix De Frutas Secas Y Semillas'),
          ('Semillas de Lino', 'Mix De Frutas Secas Y Semillas'),
          ('Mix de Semillas', 'Mix De Frutas Secas Y Semillas'),
          ('Frutos Secos', 'Mix De Frutas Secas Y Semillas'),
          ('Almendras Peladas', 'Mix De Frutas Secas Y Semillas'),
          ('Nueces Mariposas', 'Mix De Frutas Secas Y Semillas'),
          ('Pasas de Uva Rubias', 'Mix De Frutas Secas Y Semillas'),
          ('Pistachos Salados', 'Mix De Frutas Secas Y Semillas'),
          ('Avellanas Tostadas', 'Mix De Frutas Secas Y Semillas'),
          ('Copos de Maíz Clásicos', 'Copos'),
          ('Copos de Arroz', 'Copos'),
          ('Copos de Maíz Azucarados', 'Copos'),
          ('Cereales Integrales', 'Cereales'),
          ('Granola', 'Cereales'),
          ('Avena Instantánea', 'Cereales'),
          ('Barras de Cereal con Frutas', 'Cereales'),
          ('Muesli', 'Cereales'),
          ('Cereales de Salvado', 'Cereales'),
          ('Azúcar Rubia', 'Azúcar'),
          ('Azúcar Mascabo', 'Azúcar'),
          ('Azúcar Común', 'Azúcar'),
          ('Azúcar Impalpable', 'Azúcar'),
          ('Edulcorante Líquido', 'Edulcorantes'),
          ('Edulcorante en Sobres', 'Edulcorantes'),
          ('Stevia en Polvo', 'Edulcorantes'),
          ('Miel Pura', 'Miel'),
          ('Miel Industrial 5kg', 'Miel'),
          ('Jalea Real', 'Miel'),
          ('Mayonesa Regular', 'Mayonesas'),
          ('Mayonesa Light', 'Mayonesas'),
          ('Mayonesa Industrial', 'Mayonesas'),
          ('Ketchup Clásico', 'Ketchup'),
          ('Ketchup Grande', 'Ketchup'),
          ('Ketchup Doypack', 'Ketchup'),
          ('Mostaza', 'Mostazas'),
          ('Mostaza Industrial', 'Mostazas'),
          ('Mostaza Dijón', 'Mostazas'),
          ('Salsa Golf', 'Salsas'),
          ('Salsa Barbacoa', 'Salsas'),
          ('Salsa de Soja', 'Salsas'),
          ('Salsa Picante', 'Salsas'),
          ('Salsa Tártara', 'Salsas'),
          ('Salsa de Ají', 'Salsas'),
          ('Salsa para Ensaladas', 'Salsas'),
          ('Vinagreta', 'Salsas'),
          ('Salsa Pesto', 'Salsas'),
          ('Salsa Sriracha', 'Salsas'),
          ('Té Negro', 'Té'),
          ('Té Verde', 'Té'),
          ('Té de Frutas', 'Té'),
          ('Té de Boldo', 'Té'),
          ('Té de Manzanilla', 'Té'),
          ('Té Earl Grey', 'Té'),
          ('Mate Cocido', 'Mate Cocido'),
          ('Café Tostado en Grano', 'Café'),
          ('Café Instantáneo', 'Café'),
          ('Café Molido', 'Café'),
          ('Capuccino Instantáneo', 'Café'),
          ('Café en Cápsulas', 'Café'),
          ('Café Descafeinado', 'Café'),
          ('Pescado en Aceite (Atún)', 'Conservas De Pescado'),
          ('Pescado en Agua (Caballa)', 'Conservas De Pescado'),
          ('Sardinas', 'Conservas De Pescado'),
          ('Paté de Foie', 'Conservas De Carne'),
          ('Salchicha', 'Conservas De Carne'),
          ('Corned Beef en Lata', 'Conservas De Carne'),
          ('Arvejas en Lata', 'Conservas De Legumbres Y Vegetales'),
          ('Lentejas en Lata', 'Conservas De Legumbres Y Vegetales'),
          ('Choclo en Lata', 'Conservas De Legumbres Y Vegetales'),
          ('Garbanzos en Lata', 'Conservas De Legumbres Y Vegetales'),
          ('Remolacha en Rodajas', 'Conservas De Legumbres Y Vegetales'),
          ('Palmitos', 'Conservas De Legumbres Y Vegetales'),
          ('Pimientos Rojos en Lata', 'Conservas De Legumbres Y Vegetales'),
          ('Hongos en Conserva', 'Conservas De Legumbres Y Vegetales'),
          ('Pimientos Asados en Frasco', 'Vegetales en Frasco'),
          ('Hongos en Frasco', 'Vegetales en Frasco'),
          ('Choclo en Frasco', 'Vegetales en Frasco'),
          ('Harina 000', 'Harina De Trigo'),
          ('Harina 0000', 'Harina De Trigo'),
          ('Harina Integral', 'Harina Integral'),
          ('Harina de Maíz', 'Harinas Especiales'),
          ('Harina de Arroz', 'Harinas Especiales'),
          ('Harina Leudante', 'Harinas Especiales'),
          ('Harina de Centeno', 'Harinas Especiales'),
          ('Harina de Almendras', 'Harinas Especiales'),
          ('Harina de Garbanzo', 'Harinas Especiales'),
          ('Polenta Rápida', 'Harinas Especiales'),
          ('Pickles', 'Pickles'),
          ('Aceitunas Negras', 'Aceitunas'),
          ('Aceitunas Verdes', 'Aceitunas'),
          ('Aceitunas Rellenas', 'Aceitunas'),
          ('Aceitunas Descarozadas', 'Aceitunas'),
          ('Cebollas en Vinagre', 'Ajos Y Cebollas En Conserva'),
          ('Mermelada de Durazno', 'Mermeladas'),
          ('Mermelada de Frutilla', 'Mermeladas'),
          ('Mermelada de Ciruela', 'Mermeladas'),
          ('Mermelada de Damasco Light', 'Mermeladas'),
          ('Mermelada de Arándanos', 'Mermeladas'),
          ('Mermelada de Naranja', 'Mermeladas'),
          ('Mermelada de Higo', 'Mermeladas'),
          ('Mermelada de Pera', 'Mermeladas'),
          ('Mermelada Dietética', 'Mermeladas'),
          ('Dulce de Leche Clásico', 'Dulce de Leche'),
          ('Dulce de Leche Repostero', 'Dulce de Leche'),
          ('Dulce de Leche Light', 'Dulce de Leche'),
          ('Dulce de Leche familiar', 'Dulce de Leche'),
          ('Membrillo', 'Dulces'),
          ('Batata', 'Dulces'),
          ('Puré de Tomate', 'Puré De Tomate'),
          ('Puré de Tomate Institucional', 'Puré De Tomate'),
          ('Salsa Lista para Pastas', 'Salsas Y Puré De Tomate'),
          ('Salsa de Tomate Triturado', 'Salsas Y Puré De Tomate'),
          ('Tomate Pelado Entero', 'Salsas Y Puré De Tomate'),
          ('Extracto de Tomate', 'Salsas Y Puré De Tomate'),
          ('Salsa con Albahaca', 'Salsas Y Puré De Tomate'),
          ('Salsa Pizza', 'Salsas Y Puré De Tomate'),
          ('Aceite de Girasol', 'Aceites'),
          ('Aceite de Oliva Extra Virgen', 'Aceites'),
          ('Aceite de Maíz', 'Aceites'),
          ('Aceite de Soja', 'Aceites'),
          ('Aceite de Uva', 'Aceites'),
          ('Aceite de Coco', 'Aceites Especiales'),
          ('Aceite de Sésamo', 'Aceites Especiales'),
          ('Aceite de Girasol Alto Oleico', 'Aceites Especiales'),
          ('Aceite de Palta', 'Aceites Especiales'),
          ('Aceite de Canola', 'Aceites Especiales'),
          ('Vinagre de Alcohol', 'Vinagres'),
          ('Vinagre de Vino', 'Vinagres'),
          ('Vinagre de Manzana', 'Vinagres'),
          ('Vinagre Balsámico', 'Vinagres'),
          ('Sal Entrefina', 'Condimentos'),
          ('Pimienta Negra Molida', 'Condimentos'),
          ('Sal Fina', 'Condimentos'),
          ('Adobo para Pizza', 'Condimentos'),
          ('Nuez Moscada Molida', 'Condimentos'),
          ('Ajo Deshidratado', 'Condimentos'),
          ('Orégano', 'Condimentos'),
          ('Provenzal', 'Condimentos'),
          ('Ají Molido', 'Condimentos'),
          ('Pimentón Dulce', 'Condimentos'),
          ('Sal Marina Gruesa', 'Sales Y Pimientas'),
          ('Pimienta Blanca Molida', 'Sales Y Pimientas'),
          ('Sal del Himalaya', 'Sales Y Pimientas'),
          ('Arroz Largo Fino', 'Arroz'),
          ('Arroz Doble Carolina', 'Arroz'),
          ('Arroz Integral', 'Arroz'),
          ('Arroz Parboil', 'Arroz'),
          ('Arroz para Sushi', 'Arroz'),
          ('Arroz Gallo', 'Arroz'),
          ('Arroz Basmati', 'Arroz'),
          ('Arroz para Rissotto', 'Arroz'),
          ('Lentejas Secas', 'Legumbres'),
          ('Garbanzos Secos', 'Legumbres'),
          ('Porotos Negros', 'Legumbres'),
          ('Arvejas Secas', 'Legumbres'),
          ('Porotos de Soja', 'Legumbres'),
          ('Pimentón', 'Pimentón'),
          ('Canela en Polvo', 'Canela'),
          ('Comino', 'Comino'),
          ('Hojas de Laurel', 'Laurel'),
          ('Curry', 'Curry'),
          ('Jengibre en Polvo', 'Condimentos Secos'),
          ('Semillas de Sésamo', 'Condimentos Secos'),
          ('Fideos Secos Tallarines', 'Pasta Seca'),
          ('Fideos Secos Spaghetti', 'Pasta Seca'),
          ('Fideos Secos Mostacholes', 'Pasta Seca'),
          ('Fideos Secos Coditos', 'Pasta Seca'),
          ('Fideos Secos Tirabuzones', 'Pasta Seca'),
          ('Fideos Secos Dedales', 'Pasta Seca'),
          ('Fideos Secos Cabello de Ángel', 'Pasta Seca'),
          ('Fideos Secos Moñitos', 'Pasta Seca'),
          ('Fideos Secos Penne', 'Pasta Seca'),
          ('Fideos Secos Lasagna', 'Pasta Seca'),
          ('Fideos Secos Semolados', 'Pasta Seca'),
          ('Sémola', 'Pasta Seca'),
          ('Ñoquis Secos', 'Pastas Rellenas'),
          ('Canelones', 'Pastas Rellenas'),
          ('Lasaña Lista', 'Pastas Rellenas'),
          ('Ravioles Secos', 'Pastas Rellenas'),
          ('Gelatina en Polvo', 'Polvo Para Postres'),
          ('Flan en Polvo', 'Polvo Para Postres'),
          ('Mousse en Polvo', 'Polvo Para Postres'),
          ('Levadura en Polvo', 'Polvo Para Repostería'),
          ('Bicarbonato de Sodio', 'Polvo Para Repostería'),
          ('Polvo de Hornear', 'Polvo Para Repostería'),
          ('Caldo de Verdura', 'Sopas Y Caldos'),
          ('Caldo de Carne', 'Sopas Y Caldos'),
          ('Sopa Instantánea de Zapallo', 'Sopas Y Caldos'),
          ('Caldo de Pollo', 'Sopas Y Caldos'),
          ('Sopa Crema de Choclo', 'Sopas Y Caldos'),
          ('Puré de Papa Instantáneo', 'Puré Instantáneo'),
          ('Saborizante para Caldos', 'Saborizantes'),

          -- Frescos
          ('Leche Entera UAT', 'Leches'),
          ('Leche Descremada UAT', 'Leches'),
          ('Leche Semi-Descremada', 'Leches'),
          ('Leche Chocolatada', 'Leches'),
          ('Leche en Sachet', 'Leches'),
          ('Yogur Entero Sabor Frutilla', 'Yogures'),
          ('Yogur Descremado Sabor Vainilla', 'Yogures'),
          ('Yogur Entero Natural', 'Yogures'),
          ('Yogur con Cereales', 'Yogures'),
          ('Yogur Bebible', 'Yogures'),
          ('Flan de Vainilla Listo', 'Postres Lácteos'),
          ('Postre de Chocolate Listo', 'Postres Lácteos'),
          ('Gelatina Lista', 'Postres Lácteos'),
          ('Crema de Leche', 'Cremas Y Manteca'),
          ('Manteca', 'Cremas Y Manteca'),
          ('Margarina', 'Cremas Y Manteca'),
          ('Queso Cremoso', 'Quesos'),
          ('Queso Port Salut', 'Quesos'),
          ('Queso Rallado', 'Quesos'),
          ('Queso Sardo', 'Quesos'),
          ('Queso de Rallar', 'Quesos'),
          ('Queso Dambo', 'Quesos'),
          ('Queso de Barra', 'Quesos'),
          ('Queso Feteado', 'Quesos'),
          ('Queso Untable', 'Quesos'),
          ('Queso Mozzarella', 'Quesos'),
          ('Queso Provolone', 'Quesos'),
          ('Carne Molida', 'Carne Vacuna'),
          ('Bife de Chorizo', 'Carne Vacuna'),
          ('Asado', 'Carne Vacuna'),
          ('Vacío', 'Carne Vacuna'),
          ('Lomo Vacuno', 'Cortes Especiales'),
          ('Entraña', 'Cortes Especiales'),
          ('Pechito de Cerdo', 'Carne de Cerdo'),
          ('Matambrito de Cerdo', 'Carne de Cerdo'),
          ('Bondiola Fresca', 'Carne de Cerdo'),
          ('Pollo Entero', 'Aves'),
          ('Pechuga de Pollo', 'Aves'),
          ('Pata Muslo', 'Aves'),
          ('Alas de Pollo', 'Aves'),
          ('Huevos de Gallina', 'Huevos'),
          ('Huevos de Gallina Cajón', 'Huevos'),
          ('Riñones', 'Achuras'),
          ('Mollejas', 'Achuras'),
          ('Chinchulín', 'Achuras'),
          ('Morcilla', 'Achuras'),
          ('Chorizo', 'Achuras'),
          ('Salchicha Parrillera', 'Achuras'),
          ('Filet de Merluza', 'Pescado'),
          ('Salmón Fresco', 'Pescado'),
          ('Pescado del Día', 'Pescado'),
          ('Langostinos', 'Mariscos'),
          ('Mejillones', 'Mariscos'),
          ('Calamares', 'Mariscos'),
          ('Pulpo Fresco', 'Mariscos'),
          ('Vieiras', 'Mariscos'),
          ('Fideos al Huevo', 'Fideos Y Ñoquis'),
          ('Ñoquis de Papa', 'Fideos Y Ñoquis'),
          ('Tapa de Tarta Hojaldre', 'Tapas'),
          ('Tapa de Empanada Criolla', 'Tapas'),
          ('Tapa de Pascualina', 'Tapas'),
          ('Ravioles de Ricota', 'Pastas Rellenas'),
          ('Capelletis', 'Pastas Rellenas'),
          ('Jamón Cocido', 'Fiambres'),
          ('Paleta', 'Fiambres'),
          ('Salame', 'Fiambres'),
          ('Mortadela', 'Fiambres'),
          ('Panceta', 'Fiambres'),
          ('Salame Feteado', 'Fiambres'),
          ('Salchichas', 'Embutidos'),
          ('Vienesas', 'Embutidos'),
          ('Bondiola', 'Embutidos'),
          ('Manzana Roja', 'Frutas'),
          ('Banana', 'Frutas'),
          ('Naranja', 'Frutas'),
          ('Pera', 'Frutas'),
          ('Mandarina', 'Frutas'),
          ('Limón', 'Frutas'),
          ('Kiwi', 'Frutas'),
          ('Uva', 'Frutas'),
          ('Frutilla', 'Frutas'),
          ('Papa', 'Verduras'),
          ('Cebolla', 'Verduras'),
          ('Tomate', 'Verduras'),
          ('Lechuga', 'Verduras'),
          ('Zanahoria', 'Verduras'),
          ('Zapallo', 'Verduras'),
          ('Morrón Rojo', 'Verduras'),
          ('Berenjena', 'Verduras'),
          ('Calabacín', 'Verduras'),
          ('Cebolla de Verdeo', 'Verduras'),
          ('Choclo', 'Verduras'),
          ('Ajo', 'Verduras'),
          ('Palta', 'Verduras'),
          ('Rúcula', 'Hojas Verdes'),
          ('Espinaca Fresca', 'Hojas Verdes'),
          ('Acelga Fresca', 'Hojas Verdes'),
          ('Perejil Manojo', 'Hierbas Frescas'),
          ('Cilantro Manojo', 'Hierbas Frescas'),

          -- Congelados
          ('Filet de Merluza Congelado', 'Pescados'),
          ('Salmón Congelado', 'Pescados'),
          ('Camarones Congelados', 'Mariscos'),
          ('Anillos de Calamar', 'Mariscos'),
          ('Helado de Vainilla', 'Helados en Pote'),
          ('Helado de Chocolate', 'Helados en Pote'),
          ('Helado de Frutilla', 'Helados en Pote'),
          ('Helado de Crema Americana', 'Helados en Pote'),
          ('Helado de Dulce de Leche', 'Helados en Pote'),
          ('Helado Sabor Limón', 'Helados en Pote'),
          ('Helado Cremoso de Frutas', 'Helados en Pote'),
          ('Helado Industrial 10L', 'Helados en Pote'),
          ('Base de Helado Neutra', 'Helados en Pote'),
          ('Torta Helada de Chocolate', 'Postres Congelados'),
          ('Postre Helado Sabor Mousse', 'Postres Congelados'),
          ('Postre Helado Bombón Escocés', 'Postres Congelados'),
          ('Yogur Helado Frutilla', 'Postres Congelados'),
          ('Yogur Helado Natural', 'Postres Congelados'),
          ('Yogur Helado Durazno', 'Postres Congelados'),
          ('Yogur Helado con Cereales', 'Postres Congelados'),
          ('Yogur Helado Cremosísimo', 'Postres Congelados'),
          ('Helado en Palito de Crema', 'Helados En Palito'),
          ('Bombón Helado', 'Helados En Palito'),
          ('Palito de Frutas', 'Helados En Palito'),
          ('Palito de Jugo', 'Helados En Palito'),
          ('Palito de Vainilla', 'Helados En Palito'),
          ('Palito de Chocolate', 'Helados En Palito'),
          ('Palito de Crema y Chocolate', 'Helados En Palito'),
          ('Palito Doble Sabor', 'Helados En Palito'),
          ('Nuggets', 'Nuggets'),
          ('Patitas de Pollo', 'Patitas'),
          ('Bocaditos de Queso', 'Bocaditos'),
          ('Pizzas Y Pizzetas', 'Comidas Congeladas'),
          ('Pastas Congeladas', 'Comidas Congeladas'),
          ('Panificados Congelados', 'Comidas Congeladas'),
          ('Empanadas Y Tartas', 'Comidas Congeladas'),
          ('Platos Preparados', 'Comidas Congeladas'),
          ('Masa para Pizza Congelada', 'Comidas Congeladas'),
          ('Acelga', 'Vegetales Congelados'),
          ('Cebollas', 'Vegetales Congelados'),
          ('Vegetales Para Saltear', 'Vegetales Congelados'),
          ('Brócoli Congelado', 'Vegetales Congelados'),
          ('Choclo en Grano Congelado', 'Vegetales Congelados'),

          -- Limpieza
          ('Detergente para Platos', 'Detergentes'),
          ('Detergente Industrial 5L', 'Detergentes'),
          ('Limpiador Cremoso', 'Limpiadores'),
          ('Limpiador Desinfectante', 'Limpiadores'),
          ('Limpiador de Vidrios', 'Limpiadores'),
          ('Limpiador Desengrasante', 'Limpiadores'),
          ('Esponja Metálica', 'Esponjas Y Paños'),
          ('Esponja con Fibra', 'Esponjas Y Paños'),
          ('Paño de Cocina', 'Esponjas Y Paños'),
          ('Esponja Abrasiva Pack', 'Esponjas Y Paños'),
          ('Desengrasante para Hornos', 'Desengrasantes Industriales'),
          ('Detergente para Lavavajillas Industrial', 'Detergentes Especializados'),
          ('Limpiador de Inodoro', 'Limpiadores'),
          ('Desodorante de Baño', 'Limpiadores'),
          ('Pastillas para Inodoro', 'Limpiadores'),
          ('Limpiador para Baño', 'Limpiadores'),
          ('Limpiador Desinfectante de Baño', 'Limpiadores'),
          ('Limpiador de Pisos Perfumado', 'Limpiadores'),
          ('Limpiador para Madera', 'Limpiadores'),
          ('Cera para Pisos', 'Limpiadores'),
          ('Desinfectante para Pisos', 'Limpiadores'),
          ('Desinfectante de Pisos 5L', 'Limpiadores'),
          ('Jabón en Polvo para Ropa', 'Jabón'),
          ('Jabón Líquido para Ropa', 'Jabón'),
          ('Jabón Líquido para Uniformes', 'Jabón'),
          ('Suavizante de Ropa', 'Suavizantes'),
          ('Quitamanchas', 'Otros'),
          ('Aditivo para Ropa', 'Otros'),
          ('Blanqueador', 'Otros'),
          ('Quitamanchas Industrial', 'Otros'),
          ('Bolsas de Basura', 'Artículos'),
          ('Escoba', 'Artículos'),
          ('Trapeador', 'Artículos'),
          ('Guantes de Goma', 'Artículos'),
          ('Balde', 'Artículos'),
          ('Bolsas de Basura Consorcio', 'Artículos'),
          ('Trapeador Industrial', 'Artículos'),
          ('Guantes de Goma Talle Único', 'Artículos'),

          -- Equipamiento y Bazar
          ('Plato Hondo de Cerámica', 'Platos'),
          ('Plato Playo de Cerámica', 'Platos'),
          ('Plato de Postre de Cerámica', 'Platos'),
          ('Cuchara de Mesa', 'Cubiertos'),
          ('Tenedor de Mesa', 'Cubiertos'),
          ('Cuchillo de Mesa', 'Cubiertos'),
          ('Cuchara de Té', 'Cubiertos'),
          ('Vaso de Agua', 'Vasos'),
          ('Copa de Vino', 'Vasos'),
          ('Taza de Café', 'Tazas'),
          ('Taza de Té', 'Tazas'),
          ('Jarrito', 'Tazas'),
          ('Olla con Tapa', 'Ollas Y Sartenes'),
          ('Sartén Antiadherente', 'Ollas Y Sartenes'),
          ('Cacerola', 'Ollas Y Sartenes'),
          ('Batidor Manual', 'Herramientas'),
          ('Espátula de Goma', 'Herramientas'),
          ('Cuchara de Madera', 'Herramientas'),
          ('Colador', 'Herramientas'),
          ('Rallador', 'Herramientas'),
          ('Recipiente Plástico con Tapa', 'Contenedores'),
          ('Bolsas Herméticas', 'Contenedores'),
          ('Fiambrera', 'Contenedores'),
          ('Maceta de Cerámica', 'Maceteros'),
          ('Maceta de Plástico', 'Maceteros'),
          ('Tierra Fértil', 'Tierra Y Abonos'),
          ('Abono Orgánico', 'Tierra Y Abonos'),
          ('Lápiz Negro', 'Escritura'),
          ('Lapicera', 'Escritura'),
          ('Cuaderno Universitario', 'Papelería'),
          ('Hojas Rayadas', 'Papelería'),
          ('Resaltador', 'Papelería'),
          ('Cinta Adhesiva', 'Adhesivos'),
          ('Pegamento en Barra', 'Adhesivos'),
          ('Pelota de Goma', 'Juegos'),
          ('Juego de Mesa', 'Juegos'),
          ('Muñeco', 'Juegos'),
          ('Martillo', 'Herramientas'),
          ('Destornillador', 'Herramientas'),
          ('Clavos', 'Herramientas'),
          ('Tornillos', 'Herramientas'),
          ('Foco LED', 'Electricidad'),
          ('Pilas AA', 'Electricidad'),
          ('Cable Eléctrico', 'Electricidad'),

          -- Descartables
          ('Bolsa de Consorcio Reforzada', 'Bolsas'),
          ('Bolsa Ziploc', 'Bolsas'),
          ('Bolsa de Delivery Grande', 'Bolsas'),
          ('Recipiente de Aluminio', 'Envases Y Bolsas'),
          ('Recipiente de Aluminio Catering', 'Envases Y Bolsas'),
          ('Envase Telgopor para Sopas', 'Packaging'),
          ('Contenedor de Plástico con Tapa', 'Packaging'),
          ('Servilletas', 'Servilletas'),
          ('Servilletas Doble Hoja', 'Servilletas'),
          ('Cuchara Descartable', 'Cubiertos'),
          ('Tenedor Descartable', 'Cubiertos'),
          ('Cuchara Descartable Reforzada', 'Cubiertos'),
          ('Tenedor Descartable Reforzado', 'Cubiertos'),
          ('Vaso de Plástico', 'Vasos Y Platos'),
          ('Plato de Cartón', 'Vasos Y Platos'),
          ('Vaso de Polipapel para Café', 'Vasos Y Platos'),
          ('Mantel de Papel Rollo', 'Manteles'),
          ('Individuales de Papel', 'Manteles'),
          ('Sobres de Azúcar', 'Sobres y Sticks'),
          ('Sobres de Sal', 'Sobres y Sticks'),
          ('Palitos Mezcladores', 'Sobres y Sticks'),
          ('Papel de Aluminio', 'Papel Aluminio'),
          ('Papel de Aluminio Rollo Industrial', 'Papel Aluminio'),
          ('Film Autoadherente', 'Film'),
          ('Film Autoadherente Rollo', 'Film'),
          ('Rollo de Papel de Cocina', 'Papel De Cocina'),
          ('Rollo de Papel de Cocina Industrial', 'Papel De Cocina'),

          -- Bebidas
          ('Agua Mineral con Gas', 'Aguas'),
          ('Agua Mineral Sin Gas', 'Aguas'),
          ('Agua Saborizada', 'Aguas'),
          ('Agua Destilada', 'Aguas'),
          ('Soda', 'Aguas'),
          ('Gaseosa Cola', 'Gaseosas'),
          ('Gaseosa Lima-Limón', 'Gaseosas'),
          ('Gaseosa Naranja', 'Gaseosas'),
          ('Gaseosa Tónica', 'Gaseosas'),
          ('Gaseosa Cola Litro y Medio', 'Gaseosas'),
          ('Jugo de Naranja Listo', 'Jugos'),
          ('Jugo de Manzana Listo', 'Jugos'),
          ('Jugo en Polvo', 'Jugos'),
          ('Jugo de Naranja 1L', 'Jugos'),
          ('Jugo de Tomate', 'Jugos'),
          ('Agua Tónica Premium', 'Mixers Premium'),
          ('Gaseosa Ginger Ale', 'Mixers Premium'),
          ('Cerveza Rubia', 'Cervezas'),
          ('Cerveza Negra', 'Cervezas'),
          ('Cerveza IPA', 'Cervezas'),
          ('Cerveza Lager', 'Cervezas'),
          ('Cerveza Artesanal', 'Cervezas'),
          ('Cerveza Sin Alcohol', 'Cervezas'),
          ('Vino Tinto Malbec', 'Vinos'),
          ('Vino Blanco Torrontés', 'Vinos'),
          ('Vino Rosado', 'Vinos'),
          ('Vino Cabernet Sauvignon', 'Vinos'),
          ('Vino Chardonnay', 'Vinos'),
          ('Champagne Seco', 'Espumantes'),
          ('Sidra', 'Espumantes'),
          ('Vodka', 'Destilados'),
          ('Whisky', 'Destilados'),
          ('Ron', 'Destilados'),
          ('Gin', 'Destilados'),
          ('Tequila', 'Destilados'),
          ('Vermut Rojo', 'Licores Y Aperitivos'),
          ('Aperitivo Bitter', 'Licores Y Aperitivos'),
          ('Cynar', 'Licores Y Aperitivos'),
          ('Licor de Menta', 'Licores Y Aperitivos'),
          ('Fernet', 'Licores Y Aperitivos')) AS T(product_name, sub_category_level2_name)
         JOIN public.sub_category_level2 SCL2 ON SCL2.name = T.sub_category_level2_name
WHERE NOT EXISTS (SELECT 1
                  FROM public.product P
                           INNER JOIN public.sub_category_level2 SCL2_E ON P.sub_category_level2_id = SCL2_E.id
                  WHERE P.name = T.product_name
                    AND SCL2_E.name = T.sub_category_level2_name);